//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/input system/playerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""playerControls"",
    ""maps"": [
        {
            ""name"": ""standing"",
            ""id"": ""13229736-cbac-4942-bd45-4320bd5188fa"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""03b0d1bb-740d-4cdd-86a0-7b8171505e4c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""attack"",
                    ""type"": ""Button"",
                    ""id"": ""9935d0f5-c488-4b12-b5e0-b16ed15bd5d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""d3aa368d-f75c-464c-85e4-d1f92e1a6127"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c6ae75d6-0e30-4481-9456-7fb10a843bb0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""94393ef3-c2cf-4ae7-8679-d1aa0f09f255"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7320d2ab-b0aa-4be9-9ade-c3d46e233940"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4d381589-5fa9-40f3-b9c1-6f888ea8a3ff"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3918828e-a1df-40d1-881f-7c5e12e2ac83"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""knocked"",
            ""id"": ""acba10a7-b48c-4ce7-ada2-0fb6fdc8833c"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""e4108437-33f2-4d16-ba67-92c336fa59f6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7a2f6015-db1d-45ee-8b2e-4997273215b2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e966963e-d38d-47ef-9cfe-00162c963b0b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""90cca6ef-a225-4031-98ad-c6173eb37c15"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ee84b0b4-24ff-4309-acc0-a4d0384d64b6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a59fec83-c6ea-450a-a2c1-886eecf45ee1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""dead"",
            ""id"": ""9e4a8970-fae4-46b5-9d1e-4525be5acb93"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""3099a9f2-9f23-49a0-a294-7589d00080c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5c538388-3439-4eb6-80ec-5a7ce81c14dc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // standing
        m_standing = asset.FindActionMap("standing", throwIfNotFound: true);
        m_standing_move = m_standing.FindAction("move", throwIfNotFound: true);
        m_standing_attack = m_standing.FindAction("attack", throwIfNotFound: true);
        // knocked
        m_knocked = asset.FindActionMap("knocked", throwIfNotFound: true);
        m_knocked_move = m_knocked.FindAction("move", throwIfNotFound: true);
        // dead
        m_dead = asset.FindActionMap("dead", throwIfNotFound: true);
        m_dead_Newaction = m_dead.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // standing
    private readonly InputActionMap m_standing;
    private List<IStandingActions> m_StandingActionsCallbackInterfaces = new List<IStandingActions>();
    private readonly InputAction m_standing_move;
    private readonly InputAction m_standing_attack;
    public struct StandingActions
    {
        private @PlayerControls m_Wrapper;
        public StandingActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_standing_move;
        public InputAction @attack => m_Wrapper.m_standing_attack;
        public InputActionMap Get() { return m_Wrapper.m_standing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StandingActions set) { return set.Get(); }
        public void AddCallbacks(IStandingActions instance)
        {
            if (instance == null || m_Wrapper.m_StandingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StandingActionsCallbackInterfaces.Add(instance);
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
            @attack.started += instance.OnAttack;
            @attack.performed += instance.OnAttack;
            @attack.canceled += instance.OnAttack;
        }

        private void UnregisterCallbacks(IStandingActions instance)
        {
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
            @attack.started -= instance.OnAttack;
            @attack.performed -= instance.OnAttack;
            @attack.canceled -= instance.OnAttack;
        }

        public void RemoveCallbacks(IStandingActions instance)
        {
            if (m_Wrapper.m_StandingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStandingActions instance)
        {
            foreach (var item in m_Wrapper.m_StandingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StandingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StandingActions @standing => new StandingActions(this);

    // knocked
    private readonly InputActionMap m_knocked;
    private List<IKnockedActions> m_KnockedActionsCallbackInterfaces = new List<IKnockedActions>();
    private readonly InputAction m_knocked_move;
    public struct KnockedActions
    {
        private @PlayerControls m_Wrapper;
        public KnockedActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_knocked_move;
        public InputActionMap Get() { return m_Wrapper.m_knocked; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KnockedActions set) { return set.Get(); }
        public void AddCallbacks(IKnockedActions instance)
        {
            if (instance == null || m_Wrapper.m_KnockedActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KnockedActionsCallbackInterfaces.Add(instance);
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IKnockedActions instance)
        {
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IKnockedActions instance)
        {
            if (m_Wrapper.m_KnockedActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKnockedActions instance)
        {
            foreach (var item in m_Wrapper.m_KnockedActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KnockedActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KnockedActions @knocked => new KnockedActions(this);

    // dead
    private readonly InputActionMap m_dead;
    private List<IDeadActions> m_DeadActionsCallbackInterfaces = new List<IDeadActions>();
    private readonly InputAction m_dead_Newaction;
    public struct DeadActions
    {
        private @PlayerControls m_Wrapper;
        public DeadActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_dead_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_dead; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DeadActions set) { return set.Get(); }
        public void AddCallbacks(IDeadActions instance)
        {
            if (instance == null || m_Wrapper.m_DeadActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DeadActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IDeadActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IDeadActions instance)
        {
            if (m_Wrapper.m_DeadActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDeadActions instance)
        {
            foreach (var item in m_Wrapper.m_DeadActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DeadActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DeadActions @dead => new DeadActions(this);
    public interface IStandingActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
    }
    public interface IKnockedActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IDeadActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
